spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms
    username: postgres
    password: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    baseline-on-migrate: true
